### ISSUE TITLE
Foreign characters in node labels

### ISSUE THREAD

**Issue by sanyabt** [callahantiff/PheKnowLator#118]
**Describe the bug**
Hi @callahantiff, I am generating paths using search algorithms in my (extended) PheKnowLator version and noticed foreign characters (mostly Chinese characters) in some of the node labels when mapping node URIs to labels. I checked in the current build of PheKnowLator (instance-based) just to make sure it wasn't just in my build and noticed the same issue for approximately 2000 nodes (examples below).

**To Reproduce**
1. Go to pheknowlator/current_build/knowledge_graphs/instance_builds/inverse_relations/owlnets/PheKnowLator_v3.0.0_full_instance_inverseRelations_OWLNETS_NodeLabels.txt
2. Search entity: DOID_2622, UBERON_0000468, GO_0051179
3. Labels appear to be foreign characters as below.

| entity_type | integer_id | entity_uri                                      | label            | description/definition                            | synonym                                              |
|-------------|------------|-------------------------------------------------|------------------|---------------------------------------------------|------------------------------------------------------|
| NODES       | 166144     | <http://purl.obolibrary.org/obo/DOID_2622>      | 神经母细胞性肿瘤 | None                                              | None                                                 |
| NODES       | 156011     | <http://purl.obolibrary.org/obo/UBERON_0000468> | 多细胞生物       | Anatomical structure that is an individual mem... | body\|multi-cellular organism\|whole organism\|wh... |
| NODES       | 11195      | <http://purl.obolibrary.org/obo/GO_0051179>     | 定位             | Any process in which a cell, a                    |                                                      |

This is from the NodeLabels.txt file in the current_build. As far as I can tell, the issue does not appear to be due to the source ontology labels as my NodeLabels.txt file had foreign characters in labels for different nodes than the above. And a quick look up in the ontologies gives back the class names (_DOID_2622 -- neuroblastic tumor_). **Not sure if you've noticed this as well and it is already on your radar but if not I am happy to look into it more and help with the fix!** I created an issue for myself and then realized it might be useful here too.

Here is how I got the list of all nodes with foreign characters in labels from pheknowlator/current_build/knowledge_graphs/instance_builds/inverse_relations/owlnets/PheKnowLator_v3.0.0_full_instance_inverseRelations_OWLNETS_NodeLabels.txt (it's not the most efficient pandas-method so please excuse that 😅 )

```python
import re
import pandas as pd

nodes = []
nodedf = pd.read_csv('pl-build_tc/PheKnowLator_v3.0.0_full_instance_inverseRelations_OWLNETS_NodeLabels.txt', sep='\t')

for i in range(len(nodedf.index)):
    label = nodedf2.at[i, 'label']
    if isinstance(label, str):
        uri = nodedf2.at[i, 'entity_uri']
        if re.search("[\u4e00-\u9FFF]", label):
            nodes.append(uri)
#for specific examples
nodedf.loc[nodedf['entity_uri'] == nodes[0]]
```

**Desktop (please complete the following information):**
- OS: Ubuntu
- PheKnowLator version 3.0.0

**Comment by callahantiff** [comment]
No trouble at all! actually, I have a different idea. Give me a few hours and I will send you a new file. Does that sound OK?

**Comment by callahantiff** [comment]
haha, ignore the re-opening and closing of the issue, my computer just freaked out! Sorry about that 😊 .

**Comment by callahantiff** [comment]
Thank you for pointing out this bug!

**Comment by sanyabt** [comment]
Hi @callahantiff, sorry to open this again but I thought it would be better addressed on this thread - the PR namespace nodes have label = 'N/A' in the bad_node_path.json file 😅 

Examples:
'<http://purl.obolibrary.org/obo/PR_Q6V1P9>',
 '<http://purl.obolibrary.org/obo/PR_Q9NZV6-1>',
 '<http://purl.obolibrary.org/obo/PR_Q9GZL7>',
 '<http://purl.obolibrary.org/obo/PR_O76083-5>',
 '<http://purl.obolibrary.org/obo/PR_A0A087WT02>'...

About 54903 nodes have 'N/A' labels and 54844 are from the PR namespace.

**Comment by callahantiff** [comment]
haha oh boy, that's what I get for not running tests. OK, re-checking now. Be back in touch soon! 😄

**Comment by sanyabt** [comment]
Sounds good, thank you so much!
