### ISSUE TITLE
TODO: Add licenses for public data?

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#14]
**TODO:** Is it enough to cite the data sources used in the knowledge graph on the [Wiki]() or do I need to additional information like the license (if available)?

@LEHunter or @bill-baumgartner - what are your thoughts on this?

**Comment by callahantiff** [comment]
@bill-baumgartner @LEHunter -

Do you think [this](https://github.com/callahantiff/PheKnowLator/wiki/Data-Sources) is good for documentation?

**Comment by LEHunter** [comment]
Yes, nice.  You might include a brief statement about the rationale for the choices at the top of each version

**Comment by bill-baumgartner** [comment]
One minor fix: Under the `Releases` heading, the text for the release `2.0.0` link says `v1.0.0`

**Comment by callahantiff** [comment]
> Yes, nice. You might include a brief statement about the rationale for the choices at the top of each version
> […](#)
> On Sep 17, 2019, at 11:00 PM, Tiffany J. Callahan ***@***.***> wrote: @bill-baumgartner @LEHunter - Do you think this is good for documentation? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

@LEHunter - Great suggestion!

**Comment by callahantiff** [comment]
Thanks for your help with this issue. I have fixed the typo and added the suggested text. Please re-open if you feel additional information is needed.
