### ISSUE TITLE
codacy and code climate test coverage st-up

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#30]
It looks like both the Codacy and Code Climate test coverage reports are not being generated correctly. In the web dashboards for each of these apps it's stating that coverage still needs to be set-up.

@LucaCappelletti94 - would you be willing to take a look at this with me? I'm sure it is something simple I am missing.

**Comment by callahantiff** [comment]
**UPDATE:** sonar cloud and codacy have updated, but code climate measure is still not able to connect to the web app.

**Comment by LucaCappelletti94** [comment]
Sorry for the delay, I am now available to debug this.

**Comment by callahantiff** [comment]
@LucaCappelletti94 - thanks so much! I pinged you on Gitter about finding a time to meet.

**Comment by callahantiff** [comment]
Thanks again for all your help @LucaCappelletti94 ! We will stick with the coverage we have now.
