### ISSUE TITLE
HELP - Verifying Wiki Content

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#33]
Thanks so much for being willing to help with this @jwyrwa!

I am hoping that you would be willing to proof each of the following Wiki pages listed below to verify I have removed all spelling/grammar errors and to make sure that the content makes sense to you (i.e. if you were trying to use this repo would would know what to do):
- [x]  [Home](https://github.com/callahantiff/PheKnowLator/wiki/Home)  
- [x]  [KG-Construction](https://github.com/callahantiff/PheKnowLator/wiki/KG-Construction)  
- [x]  [OWL-NETS-2.0](https://github.com/callahantiff/PheKnowLator/wiki/OWL-NETS-2.0)  
- [x]  [Reasoner-Evaluation](https://github.com/callahantiff/PheKnowLator/wiki/Reasoner-Evaluation)  
- [x]  [Dependencies](https://github.com/callahantiff/PheKnowLator/wiki/Dependencies)  
- [x]  [v2.0.0](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0)  
- [x]  [v2-Data-Sources](https://github.com/callahantiff/PheKnowLator/wiki/v2-Data-Sources)

**Comment by jwyrwa** [comment]
[Home](https://github.com/callahantiff/PheKnowLator/wiki/Home)
- [ ] 'Data for this release can be downloaded [here](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#generated-output)' - This link doesn't scroll like I think you were expecting. It looks like the URL might need to be [this](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#generated-output---)
- [ ] 'We presented this work (poster) at the 15th Annual Rocky Mountain Bioinformatics Conference held December 6-8th in Snowmass, Colorado.' - Why is the poster file titled 'Rocky2017' but the link to the conference is for 2018?

**Comment by callahantiff** [comment]
> [Home](https://github.com/callahantiff/PheKnowLator/wiki/Home)
> 
> * [x]  'Data for this release can be downloaded [here](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#generated-output)' - This link doesn't scroll like I think you were expecting. It looks like the URL might need to be [this](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#generated-output---)
> * [x]  'We presented this work (poster) at the 15th Annual Rocky Mountain Bioinformatics Conference held December 6-8th in Snowmass, Colorado.' - Why is the poster file titled 'Rocky2017' but the link to the conference is for 2018?

Good catch! I have updated both URLs.

**Comment by jwyrwa** [comment]
[KG Construction](https://github.com/callahantiff/PheKnowLator/wiki/KG-Construction)

- [ ] "The OWLTools command line tool is used to download all ontologies. " - dead link

- [ ] "This tool is useful because it ensures that all ontologies imported by the ontology being downloaded are also downloaded and merged together." -- Would it be accurate saying something like this instead to be more clear? "This tool is useful because it ensures that all **secondary** ontologies imported by the **primary** ontology are also downloaded and merged together.

- [ ] "These steps are important and may require consulting with an expert." - what kinda expert?

- [ ] You bounce between using "EXAMPLE" and "Example" (underlined). Consider being consistent.

- **Wiki Page:** [Dependencies](https://github.com/callahantiff/PheKnowLator/wiki/Dependencies) 
- [ ] The beginning of the 'Dependencies' page as does the previous page says 'preparation of three documents' and then lists 8 things? What are the three documents?

- [ ] "Edge Type: An edge label (node1-node2) should match Data Sources in the ontology, class edge, and non-class edge input files." - class edge link is broken

- [ ] "Source labels: Three ; separated items (e.g.:;GO_;GO_): character to split existing labels (e.g. : in GO:1283834) and label for subject and object nodes. If the existing label is correct, type ;;." - The first sentence isn't a complete sentence. I don't understand the '_): character to split existing labels" segment. Should there be a comma and a space in between the parenthesis and colon '_), :'?

- [ ] "https://reactome.org/content/detail/" - broken link

- [ ] [Construction Approach](Construction Approach) - this links back to the KG Construction page, making a loop. I'm confused.

- [ ] What's a "UUID"?

- [ ] "An example list can be found here." - dead link

**Comment by callahantiff** [comment]
> [KG Construction](https://github.com/callahantiff/PheKnowLator/wiki/KG-Construction)
> 
> * [x]  "The OWLTools command line tool is used to download all ontologies. " - dead link
> * [x]  "This tool is useful because it ensures that all ontologies imported by the ontology being downloaded are also downloaded and merged together." -- Would it be accurate saying something like this instead to be more clear? "This tool is useful because it ensures that all **secondary** ontologies imported by the **primary** ontology are also downloaded and merged together.
> * [x]  "These steps are important and may require consulting with an expert." - what kinda expert?
> * [x]  You bounce between using "EXAMPLE" and "Example" (underlined). Consider being consistent.
> * **Wiki Page:** [Dependencies](https://github.com/callahantiff/PheKnowLator/wiki/Dependencies)
> * [x]  The beginning of the 'Dependencies' page as does the previous page says 'preparation of three documents' and then lists 8 things? What are the three documents?
> * [x]  "Edge Type: An edge label (node1-node2) should match Data Sources in the ontology, class edge, and non-class edge input files." - class edge link is broken
> * [x]  "Source labels: Three ; separated items (e.g.:;GO_;GO_): character to split existing labels (e.g. : in GO:1283834) and label for subject and object nodes. If the existing label is correct, type ;;." - The first sentence isn't a complete sentence. I don't understand the '_): character to split existing labels" segment. Should there be a comma and a space in between the parenthesis and colon '_), :'?
> * [x]  "https://reactome.org/content/detail/" - broken link
> * [x]  [Construction Approach](Construction Approach) - this links back to the KG Construction page, making a loop. I'm confused.
> * [x]  What's a "UUID"?
> * [x]  "An example list can be found here." - dead link

@jwyrwa - very helpful, thank you!! I have updated everything to reflect what you commented on. The following two points you made:
- [ ]  [Construction Approach](Construction Approach) - this links back to the KG Construction page, making a loop. I'm confused.
- [ ]  "https://reactome.org/content/detail/" - broken link

Are actually OK and functioning fine.

For the point about the source labels, I tried to improve the language and changed it to the following: 
>`Source labels: Three ;-separated items (e.g.:;GO_;GO_). The first item (i.e. ':') is a character that is used to split existing labels (e.g. : in GO:1283834), such that all characters that occur before that label are replaced by the content provided after the first and second ';' (i.e. 'GO_' and 'GO_'). If the existing label is correct, type ;;.

Does that make more sense?

**Comment by jwyrwa** [comment]
Yup.

**Comment by jwyrwa** [comment]
Should OWL always be all caps? 'owl' is used in some cases.

**Comment by callahantiff** [comment]
> Should OWL always be all caps? 'owl' is used in some cases.

It should be all caps. Are the lowercase uses in code blocks? If so, that's OK.

**Comment by jwyrwa** [comment]
[OWL NETS 2.0](https://github.com/callahantiff/PheKnowLator/wiki/OWL-NETS-2.0)

- [ ] I tried putting a dash in the title of the page, but it won't stick :(

- [ ] "A json file or dict() mapping an owl:Class to an instance of the owl:class (primarily used for PheKnowLator, for example:" - should both be 'Class' or 'class'? Is there a missing parenthesis?

**Comment by callahantiff** [comment]
> [OWL NETS 2.0](https://github.com/callahantiff/PheKnowLator/wiki/OWL-NETS-2.0)
> 
> * [ ]  I tried putting a dash in the title of the page, but it won't stick :(
- If you are talking about the header at the very top of the WIki page, then yeah that's something we can't change. Thanks for trying though!

> * [ ]  "A json file or dict() mapping an owl:Class to an instance of the owl:class (primarily used for PheKnowLator, for example:" - should both be 'Class' or 'class'? Is there a missing parenthesis?

Ahh, this part actually needs to be removed to reflect the refactoring I did to simplify this method. I have updated that section now. Thanks for catching that!

**Comment by jwyrwa** [comment]
[Reasoner Evaluation](https://github.com/callahantiff/PheKnowLator/wiki/Reasoner-Evaluation)
- I made a few grammar changes.
- I love the name 'Chainsaw' for a reasoner.
- I added my degree to throw a little more weight onto that last part.

**Comment by jwyrwa** [comment]
[v2.0.0](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0)
- [ ] "Added Data_Preparation.ipynb Jupyter Notebook to aid in creation of mapping, filtering, and labeling datasets
Added Ontology_Cleaning.ipynb Jupyter Notebook to aid in creation of mapping, filtering, and labeling datasets" - these both do the same thing? Could I just collapse it into "Added Data_Preparation.ipynb and Ontology_Cleaning.ipynb Jupyter Notebooks to aid in creation of mapping, filtering, and labeling datasets"

- [ ] [Ontologies](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#ontologies---) - all of the links are broken (404 error)

- [ ] "Relations and Inverse Relations ➞ INVERSE_RELATIONS.txt
Relations and Labels ➞ RELATIONS_LABELS.txt" - 404 errors

- [ ] "[STANDARD RELATIONS](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#knowledge-graphs---)", "[Edge Lists](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#edge-lists---)", "[Node Metadata](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#node-metadata---)" - all of the links in this table take me to a 'Create new page'

- [ ] "[Generated Output](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#generated-output---)", "[Generated Output](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#generated-output----1)" - are these (almost) exactly the same? All the same links in both sections are having the same issue I described above. Thoughts on condensing into one 'Generated Output' Section that has something like "Common Output" and then having "Unique to Subclass-Based Construction" and "Unique to Instance-Based Construction"? It'll cut down on redundancies and make it easier to maintain.

**Comment by callahantiff** [comment]
> [v2.0.0](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0)
> 
> * [x]  "Added Data_Preparation.ipynb Jupyter Notebook to aid in creation of mapping, filtering, and labeling datasets
>   Added Ontology_Cleaning.ipynb Jupyter Notebook to aid in creation of mapping, filtering, and labeling datasets" - these both do the same thing? Could I just collapse it into "Added Data_Preparation.ipynb and Ontology_Cleaning.ipynb Jupyter Notebooks to aid in creation of mapping, filtering, and labeling datasets"

Fixed, the text should not have been the same. Thanks for catching that!

> * [ ]  [Ontologies](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#ontologies---) - all of the links are broken (404 error)
Fixed!

> * [x]  "Relations and Inverse Relations ➞ INVERSE_RELATIONS.txt
>   Relations and Labels ➞ RELATIONS_LABELS.txt" - 404 errors
Fixed!

> * [x]  "[STANDARD RELATIONS](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#knowledge-graphs---)", "[Edge Lists](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#edge-lists---)", "[Node Metadata](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#node-metadata---)" - all of the links in this table take me to a 'Create new page'
Yes, sorry, these links will be down until results are finished.

> * [x]  "[Generated Output](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#generated-output---)", "[Generated Output](https://github.com/callahantiff/PheKnowLator/wiki/v2.0.0#generated-output----1)" - are these (almost) exactly the same? All the same links in both sections are having the same issue I described above. Thoughts on condensing into one 'Generated Output' Section that has something like "Common Output" and then having "Unique to Subclass-Based Construction" and "Unique to Instance-Based Construction"? It'll cut down on redundancies and make it easier to maintain.
Yes, sorry, these links will be down until results are finished. They will point to different things.

**Comment by jwyrwa** [comment]
[v2 Data Sources](https://github.com/callahantiff/PheKnowLator/wiki/v2-Data-Sources)
- I'm not even going to pretend that I understood even 1% of this page.

- [ ] "ALL_SOURCES_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes.txt" - 404 error

- [ ] "compath_cannonical_pathway_mappings.txt" - mismatch between display name and file name. Not sure which is correct.

- [ ] "[Protein Ontology](https://github.com/callahantiff/PheKnowLator/wiki/v2-Data-Sources#protein-ontology)" - o.0 is the 'ontology download' page supposed to look like that?

- [ ] "Notes: The ontology was filtered to only include human proteins using a list of of human proteins by generating a new human-only version of the ontology. Details on how this version of the ontology was generated can be found here, under the Protein Ontology section." - would it still be accurate to condense this to "A partial, human-only version of this ontology was used. Details on how this version of the ontology was generated can be found here, under the Protein Ontology section." ?

- [ ] "Merged Gene, RNA, Protein Map: Merged_gene_rna_protein_identifiers.pkl" is this meant to be indented?

- [ ] "Homepage: [BioPortal](http://data.bioontology.org/documentation)" - is this the link that you intended? I was expecting [this](https://bioportal.bioontology.org/).

- [ ] Homo_sapiens.GRCh38.98.uniprot.tsv.gz - ERR_FTP_FAILED 

- [ ] "Usage: Utilized to create edges between non-coding rna-cell and non-coding rna-anatomy edges." - edges can be made between edges?

- [ ] "Zooma was utilized to automatically the 153 unique tissues and cell types from Human Protein Atlas for all human protein-coding genes in the Human Proteome to the Cell Ontology, Cell Line Ontology, and the Uber-Anatomy Ontology." - Zooma did what automatically?

- [ ] "Parsing NCBI Gene data to obtain mappings between NCBI Gene identifiers](#ncbi-gene)," - is this supposed to be a link?

**Comment by callahantiff** [comment]
Thank you so much @jwyrwa !! This was incredibly helpful I have made all suggested changes and will now close this issue!
