### ISSUE TITLE
HELP - Verifying README Content

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#36]
Thanks so much for being willing to help with this too @jwyrwa! 🙏 

I am hoping that you can proof each of the following README pages (listed below) to verify it's free of spelling/grammar errors and to make sure that the content makes sense (i.e. if you were trying to use this repo you this content would be helpful):
- [x]  [README](https://github.com/callahantiff/PheKnowLator/blob/master/README.rst)  
- [x]  [construction_approach README](https://github.com/callahantiff/PheKnowLator/blob/master/resources/construction_approach/README.md)  
- [x]  [edge_data README](https://github.com/callahantiff/PheKnowLator/blob/master/resources/edge_data/README.md)  
- [x]  [embeddings README](https://github.com/callahantiff/PheKnowLator/blob/master/resources/embeddings/README.md)  
- [x]  [knowledge_graphs README](https://github.com/callahantiff/PheKnowLator/blob/master/resources/knowledge_graphs/README.md)  
- [x]  [node_data README](https://github.com/callahantiff/PheKnowLator/blob/master/resources/node_data/README.md)  
- [x]  [ontologies README](https://github.com/callahantiff/PheKnowLator/blob/master/resources/ontologies/README.md)  
- [x]  [owl_decoding README](https://github.com/callahantiff/PheKnowLator/blob/master/resources/owl_decoding/README.md)  
- [x]  [relations_data README](https://github.com/callahantiff/PheKnowLator/blob/master/resources/relations_data/README.md)

**Comment by jwyrwa** [comment]
[README](https://github.com/callahantiff/PheKnowLator/blob/master/README.rst)

- [ ] "The PyPi package will not be completely functional until this release is finalized." - should this be PyPI?

- [ ] "Please see the Data_Preparation.ipynb Jupyter Notebook for detailed examples of the steps used to build the v2.0.0 knowledge graph." - this links to v1.0.0 KG

- [ ] "please see the knowledge graph README for more information" - 404 link

- [ ] "resources/Master_Edge_List_Dict.json" - 404

- [ ] "resources/owl_decoding/OWL_NETS_Property_Types.txt" - 404

- [ ] "Command Line ➞ Main.py" - 404

- [ ] "Finally, pkt_kg can be run using a Docker instance. <<ADD MORE INFO HERE>>." 😄

**Comment by jwyrwa** [comment]
[construction_approach](https://github.com/callahantiff/PheKnowLator/blob/master/resources/construction_approach/README.md)
- [ ] "A pickled dictionary where the keys are node identifiers (non-ontology node data) and the values are lists of ontology class identifiers to subclass has been added to the ./resources/construction_approach/ directory." - either I'm reading this wrong or there's word(s) missing after "ontology class identifiers"

**Comment by jwyrwa** [comment]
[edge_data README](https://github.com/callahantiff/PheKnowLator/blob/master/resources/edge_data/README.md)

- [ ] "edge_source_list.txt", "resources/edge_data/ chemical-disease_CTD_chemicals_diseases.tsv chemical-gene_CTD_chem_gene_ixns.tsv chemical-phenotype_CTD_chemicals_diseases.tsv chemical-protein_CTD_chem_gene_ixns.tsv" - are these all meant to be links?

**Comment by jwyrwa** [comment]
[embeddings README](https://github.com/callahantiff/PheKnowLator/blob/master/resources/embeddings/README.md)
- [ ] "Jupyter Notebook: Main.ipynb" - 404

- [ ] "an implementation of the original algorithm in C ++, with some improvements to speed up initialize the hierarchical softmax tree that was developed by Anton Tsitsulin." - this sentence makes sense up until "up".

- [ ] "For the Headers, the sub-directory called Boost at the top-level of the walking-rdf-and-owl-master directory." - missing word(s)

**Comment by jwyrwa** [comment]
[knowledge_graphs README](https://github.com/callahantiff/PheKnowLator/blob/master/resources/knowledge_graphs/README.md)
- nada, looks great!

**Comment by jwyrwa** [comment]
[node_data README](https://github.com/callahantiff/PheKnowLator/blob/master/resources/node_data/README.md)
👍

**Comment by jwyrwa** [comment]
Done!

**Comment by callahantiff** [comment]
Thanks so much @jwyrwa for all of your edits, I really appreciate it!!!
