### ISSUE TITLE
TODO: Publish Docker to Docker Hub

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#43]
Publish Docker to [Docker Hub](https://hub.docker.com/), when creating v2.0.0 release.

**Comment by callahantiff** [comment]
Update README for how to use project Docker. Good examples from @bill-baumgartner included below:

https://github.com/UCDenver-ccp/craft-shared-tasks/wiki/Concept-Annotation-Task-Evaluation

https://github.com/UCDenver-ccp/craft-shared-tasks/wiki/Building-the-CRAFT-evaluation-Docker-container

**Comment by callahantiff** [comment]
@bill-baumgartner  - I am drafting the content that we will ultimately add to the README for utilizing Docker. I thought I would run it by you here. Would you mind taking a look at let me know what you think?

**Notes**
- The DockerHub link is not yet active and will be updated with the correct link once our container is uploaded.  
- References to "above" will make sense once this information is added back to the README.

<br>

***  

### Docker  
In order to utilize the Dockerized version of the code, please make sure that you have downloaded the newest version of [Docker](https://docs.docker.com/get-docker/). There are two ways to utilize Docker with this repository:  
- Obtain the pre-built Docker container from [DockerHub]()  
- Build the Container  

**Build the Container**  
To build the PheKnowLator Docker container:
- Download a stable release of this repository or clone this repository to get the most up-to-date version  
- Unpack the repository downloaded (if necessary), then execute the following commands to build the container:

```bash
cd /path/to/PheKnowLator (Note, this is the directory containing the Dockerfile file)
docker build -t pkt:[VERSION] 
```

**Running the Container**  
To run PheKnowLator from outside of the container (after obtaining a prebuilt container or after building the container locally), run the following code from the project root (i.e. `PheKnowLator/`):  

```bash
docker run --name pkt_example --rm -ti -v /local/path/to/PheKnowLator/resources/knowledge_graphs/:/PheKnowLator/resources/knowledge_graphs/ pkt:2.0.0 --app subclass --kg full --nde yes --rel yes --owl no --kgm yes
``` 

_NOTES_:  
- The Docker container cannot write to an encrypted filesystem, however, so please make sure `/local/path/to/PheKnowLator/resources/knowledge_graphs` references a directory that is not encrypted    
- The example shown above builds a full version of the knowledge graph using the subclass construction approach with node metadata, inverse relations, and decoding of OWL classes. See the `Running the pkt Library` section for more information on the parameters that can be passed to PheKnowLator.

***

**Comment by bill-baumgartner** [comment]
Looks good. I have three comments:
1) There is a missing dot at the end of the docker build command, it should be:
`docker build -t pkt:[VERSION] .`
2) The `docker run` command can work from any directory so "run the following code from the project root (i.e. PheKnowLator/):" is not necessary, and may not be possible if the user doesn't download the PheKnowLator code.
3) I think the Dockerfile needs to be changed at this point such that it doesn't download the code from GitHub, but instead uses the `COPY` command to import into the container. This way, any local changes to the code will be automatically imported. I think this is the expected behavior and may lead to confusion if we are instead pulling in the code from GitHub each time.

**Comment by callahantiff** [comment]
> Looks good. I have three comments:
> 
> 1. There is a missing dot at the end of the docker build command, it should be:
>    `docker build -t pkt:[VERSION] .`
> 2. The `docker run` command can work from any directory so "run the following code from the project root (i.e. PheKnowLator/):" is not necessary, and may not be possible if the user doesn't download the PheKnowLator code.
> 3. I think the Dockerfile needs to be changed at this point such that it doesn't download the code from GitHub, but instead uses the `COPY` command to import into the container. This way, any local changes to the code will be automatically imported. I think this is the expected behavior and may lead to confusion if we are instead pulling in the code from GitHub each time.

Thanks @bill-baumgartner! I have fixed the first two points and will work on the third. I need to think about what assumptions we will impose when utilizing the `COPY` approach. I will put it on the list for our meeting tomorrow.

**Comment by callahantiff** [comment]
@bill-baumgartner - Do we need to have two versions 1 for the CI/CD and one that people can download independently and run on their own? Perhaps we can just publish one to DockerHub and that can fulfill both use cases?
