### ISSUE TITLE
TODO: Finalize KG Construction Survey

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#54]
I am working on the qualitative component of our evaluation and am requesting your review of a Google Form I created to help organize this information. 

**TODO:** Please take a look at the Google Form (link to form can be found **[`here`](https://docs.google.com/document/d/1ykgMNMFBLUOoWIChidtBJDPKf_GojxuXIU7MJoff4hM/edit?disco=AAAAGiqskGE)**) and let me know if you have any edits by **11:59pm on May 22, 2020**?

**Comment by LEHunter** [comment]
Pointer was to the paper, not a form.

On May 21, 2020, at 2:54 PM, Tiffany J. Callahan <notifications@github.com<mailto:notifications@github.com>> wrote:



I am working on the qualitative component of our evaluation and am requesting your review of a Google Form I created to help organize this information.

TODO: Please take a look at the Google Form (link to form can be found here<https://docs.google.com/document/d/1ykgMNMFBLUOoWIChidtBJDPKf_GojxuXIU7MJoff4hM/edit?disco=AAAAGiqskGE>) and let me know if you have any edits by 11:59pm on May 22, 2020?

**Comment by LEHunter** [comment]
I found it.  Looks quite comprehensive. A few thoughts:  In section 3, some systems don’t have explicit releases.  In section 5, do you want to check for clinical data sources?  I’m not sure what the Scale question means — perhaps something about Maximum size of inputs?  Also maybe number of inputs (can it assemble multiple ontologies into a coherent KG)? In section 6 I might add cloud compatibility as well as OS. Section 9 should include licensing terms more generally than just open/not.  Not sure what you are getting at in section 8 — is this about having a docker container? In section 10, do any have a literate programming (e.g. Jupyter / R Markdown) tutorial?

L

**Comment by callahantiff** [comment]
> I found it. Looks quite comprehensive. A few thoughts: In section 3, some systems don’t have explicit releases. In section 5, do you want to check for clinical data sources? I’m not sure what the Scale question means — perhaps something about Maximum size of inputs? Also maybe number of inputs (can it assemble multiple ontologies into a coherent KG)? In section 6 I might add cloud compatibility as well as OS. Section 9 should include licensing terms more generally than just open/not. Not sure what you are getting at in section 8 — is this about having a docker container? In section 10, do any have a literate programming (e.g. Jupyter / R Markdown) tutorial? L

Thanks @LEHunter!

I went ahead and made the following changes:
- **Section 3:** I added language to include "release" and "version"  
- **Section 5:**   
  - I added clinical data  
  - I added a question to handle number of inputs
  - I think the preview version of the form is confusion. I am only including "Yes", "No", and "Other" as response options  
- **Section 6:** I added cloud compatibility  
- **Section 8:** Exactly. I added some examples to the question to make it more clear
- **Section 9:** License types have been added  
- **Section 10:** Added your suggestion

Better?

**Comment by LEHunter** [comment]
Yes, quite comprehensive. .

On May 21, 2020, at 4:23 PM, Tiffany J. Callahan <notifications@github.com<mailto:notifications@github.com>> wrote:



I found it. Looks quite comprehensive. A few thoughts: In section 3, some systems don’t have explicit releases. In section 5, do you want to check for clinical data sources? I’m not sure what the Scale question means — perhaps something about Maximum size of inputs? Also maybe number of inputs (can it assemble multiple ontologies into a coherent KG)? In section 6 I might add cloud compatibility as well as OS. Section 9 should include licensing terms more generally than just open/not. Not sure what you are getting at in section 8 — is this about having a docker container? In section 10, do any have a literate programming (e.g. Jupyter / R Markdown) tutorial? L

Thanks @LEHunter<https://github.com/LEHunter>!

I went ahead and made the following changes:

  *   Section 3: I added language to include "release" and "version"
  *   Section 5:
     *   I added clinical data
     *   I added a question to handle number of inputs
     *   I think the preview version of the form is confusion. I am only including "Yes", "No", and "Other" as response options
  *   Section 6: I added cloud compatibility
  *   Section 8: Exactly. I added some examples to the question to make it more clear
  *   Section 9: License types have been added
  *   Section 10: Added your suggestion

Better?

**Comment by bill-baumgartner** [comment]
* Section 1: Most recent date of interaction with code repository
  * do we need a ">1 year" response?
* Section 2, step 1
  * is this separate from instructions for how to download data?  Must it be an automatic process?
* Section 2, steps 2/3
  * can't an edge list or edge set be considered a knowledge graph? What's the distinction?
* Section 5
  * do you want to capture the data sources used by each method?
* Section 9
  * I see "docker" listed in section 8, but I think it applies to section 9 too. Similarly, if it's python code you might ask if it's in PyPI. If it's Java code, is the code available in a Maven repository, etc. I guess what I'm really getting at is perhaps a question related to the ease of installation of the system.

**Comment by callahantiff** [comment]
> * Section 1: Most recent date of interaction with code repository
>   
>   * do we need a ">1 year" response?
> * Section 2, step 1
>   
>   * is this separate from instructions for how to download data?  Must it be an automatic process?
> * Section 2, steps 2/3
>   
>   * can't an edge list or edge set be considered a knowledge graph? What's the distinction?
> * Section 5
>   
>   * do you want to capture the data sources used by each method?
> * Section 9
>   
>   * I see "docker" listed in section 8, but I think it applies to section 9 too. Similarly, if it's python code you might ask if it's in PyPI. If it's Java code, is the code available in a Maven repository, etc. I guess what I'm really getting at is perhaps a question related to the ease of installation of the system.

Thanks @bill-baumgartner! These are great suggestions! I went ahead and 
- **Section 1:** Great catch, I added "> 1 year" 
- **Section 2, step 1:**  I added two versions of "Yes" to capture whether or not the process was automated
- **Section 2, steps 2/3:** You could theoretically have edge lists that were disjoint and thus could not be combined into a KG. Most of the methods I have seen seem to have an explicit kg construction step. For `pkt_kg` were generate edge lists that if assembled without running our KG construction process would result in very different graphs.
- **Section 5:** Great idea, a question has been added to capture this idea.   
- **Section 9:**   
  - Agreed! Docker has been added to Section 9
  - Great catch -- A question has been added to ask about library/packages or. other services to ease installation

Do you want to see it again before I start the evaluation?

**Comment by callahantiff** [comment]
@LEHunter and @bill-baumgartner 
Last task, I'd like to run the list of methods I will apply the survey to by you (n=25 methods). You can find the list with links [`here`](https://docs.google.com/spreadsheets/d/1qs178i8Il67rfYUAnMlnjB-5ewexhkKlJ-yrRJhe0M8/edit#gid=1126641709&range=A2:F27). Please be patient when opening this link, it works but may take a few seconds to load.

**Comment by bill-baumgartner** [comment]
I was confused until I scrolled and saw the `Eligible` column. That is quite a list! Looks good overall. I see you have one called `Metabolomics-in-SPOKE`. Should you also include [SPOKE](https://spoke.ucsf.edu/) itself?

**Comment by callahantiff** [comment]
> I was confused until I scrolled and saw the `Eligible` column. That is quite a list! Looks good overall. I see you have one called `Metabolomics-in-SPOKE`. Should you also include [SPOKE](https://spoke.ucsf.edu/) itself?

I would, but they don't seem to have a public repository. I'm happy to list that as the reason they are not included though.

**Comment by LEHunter** [comment]
Yep, do say that.  They say they are going to release a COVID SPOKE, but I haven’t seen that either.

On May 26, 2020, at 3:53 PM, Tiffany J. Callahan <notifications@github.com<mailto:notifications@github.com>> wrote:



I was confused until I scrolled and saw the Eligible column. That is quite a list! Looks good overall. I see you have one called Metabolomics-in-SPOKE. Should you also include SPOKE<https://spoke.ucsf.edu/> itself?

I would, but they don't seem to have a public repository. I'm happy to list that as the reason they are not included though.

**Comment by callahantiff** [comment]
OK, I think we can close this now. I will work on completing the survey over the next week. Thank you both for your help!
