### ISSUE TITLE
Coding: Improve storage of original triples when running OWL-NETS

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/PheKnowLator#56]
### TASK  
**Task Type:** [`CODEBASE`](https://github.com/callahantiff/PheKnowLator/projects/8#card-51636107)

Improve the storage of removed OWL semantics when running [OWL-NETS](https://github.com/callahantiff/PheKnowLator/wiki/OWL-NETS-2.0) version of the build. Remove dictionary constraint for something network-based.

#### TODO  
- [ ] Come up with a better solution to handle triples removed from the full KG when creating `OWL-NETS`  
  - Information that is compressed when converting a class from `OWL` to `OWL-NETS`  
  - Information that is purposefully ignored or deleted (i.e. specific triples, disjointness)   
- [ ] Determine if we want to update OWL-NETS to follow any of the OWL to RDF specifications mentioned in the [OWL2Vec*](https://arxiv.org/pdf/2009.14654.pdf) paper: 
  - W3C Defined Graph Mapping ([here](https://www.w3.org/TR/owl2-mapping-to-rdf/))   
  - Projection rule-based approach ([here](http://ceur-ws.org/Vol-2456/paper9.pdf))   

@bill-baumgartner - can we talk about the other OWL transformations soon? From what I can tell, OWL-NETS is a more extreme version of the transformations described above.

**Comment by callahantiff** [comment]
@LEHunter - Would love your opinion on the property graph created by OWL2Vec* and what we do with OWL-NETS (V2 described [here](https://github.com/callahantiff/PheKnowLator/wiki/OWL-NETS-2.0)). Seems like we are creating a more extreme version. Perhaps we should call OWL-NETS something other than a property graph?

I'm tempted to import their method to derive their property graph version so we can compare it to OWL-NETS and the full graph builds. Since their code is in Python too, it should not be too difficult. Something to think about. 😄

**Comment by LEHunter** [comment]
I'm not sure I understand your question.  A "property graph" as far as I can tell is just a graph with typed and directed edges.  

I totally agree about including the OWL2VEC* method in the graph builds for comparison purposes.  I'd be surprised if paper reviewers didn't insist on it anyway.

**Comment by callahantiff** [comment]
> I'm not sure I understand your question. A "property graph" as far as I can tell is just a graph with typed and directed edges.

Thanks @LEHunter! I think I was focused on the wrong thing. I agree that we are good on this. 

> I totally agree about including the OWL2VEC* method in the graph builds for comparison purposes. I'd be surprised if paper reviewers didn't insist on it anyway.

Sounds good. Depending on how easy/hard it is to import their code (it's not the easiest to read), I may not formally include it as a build parameter for the next build. That said, we will plan to include it for the paper.

**Comment by callahantiff** [comment]
After speaking with @bill-baumgartner - we will be holding off on making further updates to `OWL-NETS`, especially since the method is functioning just fine. Once the initial paper is complete this issue will be reconsidered.

**Comment by callahantiff** [comment]
Closing this issue for now, have a temporary workaround. Solution is described on the owl-nets wiki.
